### ISSUE TITLE
Mobile-first Dashboard

### ISSUE THREAD

**Issue by dpdonohue** [biologio/biolog#1]
We need a header bar as seen here
http://biolog.meteor.com/

Menu options are selected from a standard menu button in the header bar

Could use the code I have in this project
https://github.com/realdbio/biolog
or could select a different starting point

**Comment by dpdonohue** [comment]
I suggest we consider starting the new project with some Meteor starter/boilerplate template?
This would give us the right directory structure etc.

See this page
https://gentlenode.com/journal/meteor-22-the-best-meteor-packages-you-must-know-to-code-faster-than-ever/52
It lists many good packages.  I am not using many of them.  I am using easy-search and a few others.
It lists 3 good boiler plates.  
I have used Ionic Framework in a past project and I wonder if this is a good choice.
Ionic is nice for developing apps.  Downsides of Ionic are (1) It is angular so you still need a separate back end web service, and (2) it is mobile only.  Does not work in general browsers very well at all.  Meteor-ionic might have the best of both worlds.  But it might just add more complexity.
This looked like the best boilerplate, including several packages that looked great to me
https://github.com/matteodem/meteor-boilerplate

**Comment by dipakyadav** [comment]
1. we are not going to use Meteor-ionic since its in beta.
2. i will have to look in to all [meteor-boilerplage](https://github.com/matteodem/meteor-boilerplate) bcz for the UI its using the package [meteor-semantic-ui] (https://github.com/nooitaf/meteor-semantic-ui) which is depricated, and we don't want to use some thing that is not supported in the future.
3. the [meteor-boilerplage](https://github.com/matteodem/meteor-boilerplate) contains large lists of packages do we need all ?, i don't think so , its always good to start with minimal and extend it as per need, instead of putting lots of stuffs at once and we don't know what is going on in side.
4. its Ok if we are not using AngularJS, but still we will need to use some kind of Responsive UI package i.e., Bootstrap or Semantic UI, i have used Bootstrap most but Semantic seems to more smooth.

we will be using  [this as a guide] (https://gentlenode.com/journal/meteor-22-the-best-meteor-packages-you-must-know-to-code-faster-than-ever/52)  for our project and will add packages as and when needed.

**Comment by dpdonohue** [comment]
OK Dipak I agree with your comments and your strategy.
Dave


On Tue, Apr 28, 2015 at 10:47 PM, dipakyadav <notifications@github.com>
wrote:

>
>    1. we are not going to use Meteor-ionic since its in beta.
>    2. i will have to look in to all meteor-boilerplage
>    <https://github.com/matteodem/meteor-boilerplate> bcz for the UI its
>    using the package meteor-semantic-ui
>    <https://github.com/nooitaf/meteor-semantic-ui> which is depricated,
>    and we don't want to use some thing that is not supported in the future.
>    3. the meteor-boilerplage
>    <https://github.com/matteodem/meteor-boilerplate> contains large lists
>    of packages do we need all ?, i don't think so , its always good to start
>    with minimal and extend it as per need, instead of putting lots of stuffs
>    at once and we don't know what is going on in side.
>    4. its Ok if we are not using AngularJS, but still we will need to use
>    some kind of Responsive UI package i.e., Bootstrap or Semantic UI, i have
>    used Bootstrap most but Semantic seems to more smooth.
>
> we will be using this as a guide
> <https://gentlenode.com/journal/meteor-22-the-best-meteor-packages-you-must-know-to-code-faster-than-ever/52>
> for our project and will add packages as and when needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biologio/biolog/issues/1#issuecomment-97289174>.
>



-- 
*David Donohue, MD, FACP*
*Progressive Health of Delaware*
*302-543-5454*
*3519 Silverside Rd, Ste 200*
*Ridgely Bldg.*
*Wilmington, DE 19810*
*Fax 302-327-4200*
*www.progressivehealthofde.com <http://www.progressivehealthofde.com/>*

PRIVILEGED AND CONFIDENTIAL:  This document and the information contained
herein are confidential and protected from disclosure pursuant to federal
law.  This message is intended only for the use of the Addressee(s) and may
contain information that is PRIVILEGED and CONFIDENTIAL. If you are not the
intended recipient, you are hereby notified that the use dissemination, or
copying of this information is strictly prohibited.  If you have received
this communication in error, please erase all copies of the message and its
attachments and notify the sender immediately.

**Comment by dpdonohue** [comment]
Sematic-ui works well
